from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]

HIST_DIR = (
    ROOT
    / "data"
    / "processed"
    / "publication_groundwater"
)

POST_DIR = (
    ROOT
    / "data"
    / "processed"
    / "post2021"
)

DIAG_DIR = (
    ROOT
    / "outputs"
    / "diagnostics"
    / "post2021"
)

CLEAN_IN = HIST_DIR / "groundwater_clean.csv"
META_IN = HIST_DIR / "groundwater_station_metadata.csv"
HIST_ANNUAL_IN = HIST_DIR / "groundwater_annual_measures.csv"

OUT = POST_DIR / "groundwater_annual_measures_2008_2023.csv"
QA_OUT = DIAG_DIR / "post2021_groundwater_annual_availability.csv"
REPRO_QA_OUT = (
    DIAG_DIR
    / "groundwater_annual_extension_historical_reproduction_qa.csv"
)

START_YEAR = 2008
END_YEAR = 2023
HIST_END_YEAR = 2021

EXPECTED_ISS_STATIONS = 37


def yearly_record(g: pd.DataFrame) -> pd.Series:
    """
    Exact annual-summary definitions copied from the frozen
    historical production pipeline.

    No groundwater/flooding model logic occurs here.
    """

    g = g.sort_values("date")

    janfeb = g[g["month"].isin([1, 2])]
    janmar = g[g["month"].isin([1, 2, 3])]
    aprmay = g[g["month"].isin([4, 5])]
    aug = g[g["month"] == 8]
    jja = g[g["month"].isin([6, 7, 8])]

    out = {
        "gw_obs_n": len(g),
        "gw_janfeb_n": len(janfeb),
        "gw_janfeb_mean_m": janfeb["gw_depth_m"].mean(),
        "gw_janmar_mean_m": janmar["gw_depth_m"].mean(),
        "gw_aprmay_mean_m": aprmay["gw_depth_m"].mean(),
        "gw_jja_mean_m": jja["gw_depth_m"].mean(),
        "gw_aug_n": len(aug),
        "gw_aug_mean_m": aug["gw_depth_m"].mean(),
    }

    if len(janfeb):
        r = janfeb.iloc[-1]

        out.update(
            {
                "gw_pre_last_janfeb_m": r["gw_depth_m"],
                "gw_pre_last_janfeb_date":
                    r["date"].date().isoformat(),
                "gw_pre_last_janfeb_doy": r["doy"],
            }
        )
    else:
        out.update(
            {
                "gw_pre_last_janfeb_m": np.nan,
                "gw_pre_last_janfeb_date": None,
                "gw_pre_last_janfeb_doy": np.nan,
            }
        )

    if len(aug):
        first = aug.iloc[0]
        last = aug.iloc[-1]

        target = pd.Timestamp(
            year=int(g["date"].dt.year.iloc[0]),
            month=8,
            day=23,
        )

        nearest = aug.iloc[
            (aug["date"] - target)
            .abs()
            .argmin()
        ]

        out.update(
            {
                "gw_aug_first_m": first["gw_depth_m"],
                "gw_aug_first_date":
                    first["date"].date().isoformat(),
                "gw_aug_first_doy": first["doy"],
                "gw_aug_last_m": last["gw_depth_m"],
                "gw_aug_last_date":
                    last["date"].date().isoformat(),
                "gw_aug_nearest_aug23_m":
                    nearest["gw_depth_m"],
                "gw_aug_nearest_aug23_date":
                    nearest["date"].date().isoformat(),
                "gw_aug_nearest_aug23_doy":
                    nearest["doy"],
            }
        )
    else:
        out.update(
            {
                "gw_aug_first_m": np.nan,
                "gw_aug_first_date": None,
                "gw_aug_first_doy": np.nan,
                "gw_aug_last_m": np.nan,
                "gw_aug_last_date": None,
                "gw_aug_nearest_aug23_m": np.nan,
                "gw_aug_nearest_aug23_date": None,
                "gw_aug_nearest_aug23_doy": np.nan,
            }
        )

    return pd.Series(out)


def compare_historical(
    extended: pd.DataFrame,
    historical: pd.DataFrame,
) -> pd.DataFrame:
    """
    Verify that 2008-2021 generated by this extension reproduces
    the frozen historical annual-measures artifact.
    """

    generated = extended.loc[
        extended["year"].between(
            START_YEAR,
            HIST_END_YEAR,
        )
    ].copy()

    historical = historical.copy()

    key = ["station", "year"]

    if generated.duplicated(key).any():
        raise AssertionError(
            "Duplicate station-year in generated historical table."
        )

    if historical.duplicated(key).any():
        raise AssertionError(
            "Duplicate station-year in frozen historical table."
        )

    generated = generated.sort_values(key).reset_index(drop=True)
    historical = historical.sort_values(key).reset_index(drop=True)

    if len(generated) != len(historical):
        raise AssertionError(
            "Historical reproduction row-count mismatch: "
            f"generated={len(generated)}, "
            f"frozen={len(historical)}"
        )

    if not generated[key].equals(historical[key]):
        raise AssertionError(
            "Historical station-year keys do not reproduce."
        )

    common = [
        c
        for c in historical.columns
        if c in generated.columns
    ]

    rows = []

    for col in common:
        if col in key:
            continue

        a = historical[col]
        b = generated[col]

        if (
            pd.api.types.is_numeric_dtype(a)
            and pd.api.types.is_numeric_dtype(b)
        ):
            a_num = pd.to_numeric(a, errors="coerce")
            b_num = pd.to_numeric(b, errors="coerce")

            equal = np.isclose(
                a_num.to_numpy(dtype=float),
                b_num.to_numpy(dtype=float),
                equal_nan=True,
                rtol=0,
                atol=1e-12,
            )

        else:
            a_str = a.astype("string").fillna("<NA>")
            b_str = b.astype("string").fillna("<NA>")

            equal = (
                a_str.to_numpy()
                == b_str.to_numpy()
            )

        mismatch_n = int(
            (~equal).sum()
        )

        rows.append(
            {
                "column": col,
                "rows_compared": len(equal),
                "mismatch_n": mismatch_n,
                "exact_reproduction": mismatch_n == 0,
            }
        )

    qa = pd.DataFrame(rows)

    if not qa["exact_reproduction"].all():
        bad = qa.loc[
            ~qa["exact_reproduction"]
        ]

        raise AssertionError(
            "Extended annual builder does not reproduce "
            "the frozen 2008-2021 artifact:\n"
            + bad.to_string(index=False)
        )

    return qa


def main() -> None:
    POST_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    DIAG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    clean = pd.read_csv(
        CLEAN_IN,
        parse_dates=["date"],
    )

    station_meta = pd.read_csv(
        META_IN
    )

    historical = pd.read_csv(
        HIST_ANNUAL_IN
    )

    iss_stations = sorted(
        station_meta.loc[
            station_meta["aquifer_group"] == "ISS",
            "station",
        ]
    )

    if len(iss_stations) != EXPECTED_ISS_STATIONS:
        raise AssertionError(
            f"Expected {EXPECTED_ISS_STATIONS} ISS stations; "
            f"found {len(iss_stations)}."
        )

    iss = clean.loc[
        (clean["aquifer_group"] == "ISS")
        & clean["year"].between(
            START_YEAR,
            END_YEAR,
        )
    ].copy()

    grid = pd.MultiIndex.from_product(
        [
            iss_stations,
            range(
                START_YEAR,
                END_YEAR + 1,
            ),
        ],
        names=[
            "station",
            "year",
        ],
    ).to_frame(
        index=False
    )

    monthly = (
        iss.groupby(
            [
                "station",
                "year",
                "month",
            ]
        )["gw_depth_m"]
        .mean()
        .unstack("month")
        .rename(
            columns={
                m: f"gw_m{m:02d}_mean_m"
                for m in range(1, 13)
            }
        )
        .reset_index()
    )

    annual_records = (
        iss.groupby(
            [
                "station",
                "year",
            ],
            group_keys=False,
        )
        .apply(
            yearly_record,
            include_groups=False,
        )
        .reset_index()
    )

    annual = (
        grid.merge(
            annual_records,
            on=[
                "station",
                "year",
            ],
            how="left",
            validate="one_to_one",
        )
        .merge(
            monthly,
            on=[
                "station",
                "year",
            ],
            how="left",
            validate="one_to_one",
        )
        .merge(
            station_meta,
            on="station",
            how="left",
            validate="many_to_one",
        )
    )

    expected_rows = (
        EXPECTED_ISS_STATIONS
        * (
            END_YEAR
            - START_YEAR
            + 1
        )
    )

    if len(annual) != expected_rows:
        raise AssertionError(
            f"Expected {expected_rows} station-years; "
            f"found {len(annual)}."
        )

    # ---------------------------------------------------------
    # Critical integrity test:
    # reproduce the frozen 2008-2021 annual artifact exactly.
    # ---------------------------------------------------------

    reproduction_qa = compare_historical(
        annual,
        historical,
    )

    print(
        "Historical annual-measures reproduction: PASS"
    )
    print(
        f"  columns reproduced: "
        f"{len(reproduction_qa):,}"
    )
    print(
        "  mismatches: 0"
    )
    print("")

    # ---------------------------------------------------------
    # Availability only.
    # Do not print groundwater-depth values.
    # ---------------------------------------------------------

    post = annual.loc[
        annual["year"].isin(
            [2022, 2023]
        )
    ].copy()

    post[
        "complete_pre_plus_augmean"
    ] = (
        post["gw_pre_last_janfeb_m"].notna()
        & post["gw_aug_mean_m"].notna()
    )

    post[
        "complete_pre_plus_aug23"
    ] = (
        post["gw_pre_last_janfeb_m"].notna()
        & post[
            "gw_aug_nearest_aug23_m"
        ].notna()
    )

    rows = []

    for year in [2022, 2023]:
        y = post.loc[
            post["year"] == year
        ]

        rows.append(
            {
                "year": year,
                "iss_station_universe_n":
                    EXPECTED_ISS_STATIONS,
                "stations_any_obs_n": int(
                    (y["gw_obs_n"].fillna(0) > 0).sum()
                ),
                "stations_janfeb_n": int(
                    y["gw_pre_last_janfeb_m"]
                    .notna()
                    .sum()
                ),
                "stations_augmean_n": int(
                    y["gw_aug_mean_m"]
                    .notna()
                    .sum()
                ),
                "stations_aug23_n": int(
                    y["gw_aug_nearest_aug23_m"]
                    .notna()
                    .sum()
                ),
                "complete_pre_plus_augmean_n":
                    int(
                        y[
                            "complete_pre_plus_augmean"
                        ].sum()
                    ),
                "complete_pre_plus_aug23_n":
                    int(
                        y[
                            "complete_pre_plus_aug23"
                        ].sum()
                    ),
            }
        )

    availability = pd.DataFrame(
        rows
    )

    repeated = (
        post.loc[
            post["complete_pre_plus_aug23"]
        ]
        .groupby("station")["year"]
        .nunique()
        .value_counts()
        .sort_index()
        .rename_axis(
            "complete_years_per_station"
        )
        .reset_index(
            name="stations_n"
        )
    )

    if len(repeated):
        repeat_text = "; ".join(
            f"{int(r.complete_years_per_station)} year(s): "
            f"{int(r.stations_n)} station(s)"
            for r in repeated.itertuples(
                index=False
            )
        )
    else:
        repeat_text = "none"

    availability[
        "repeated_complete_aug23_distribution"
    ] = repeat_text

    annual.to_csv(
        OUT,
        index=False,
    )

    reproduction_qa.to_csv(
        REPRO_QA_OUT,
        index=False,
    )

    availability.to_csv(
        QA_OUT,
        index=False,
    )

    print(
        "POST-2021 GROUNDWATER AVAILABILITY — COUNTS ONLY"
    )
    print(
        availability.to_string(
            index=False
        )
    )

    print("")
    print(
        "No groundwater depths were printed."
    )
    print(
        "No flooding exposure was merged."
    )
    print(
        "No association model was fitted."
    )
    print("")
    print(f"Wrote: {OUT}")
    print(f"Wrote: {REPRO_QA_OUT}")
    print(f"Wrote: {QA_OUT}")


if __name__ == "__main__":
    main()